version: 0.0
os: linux
files:
  - source: version/version.txt
    destination: /var/www/html/version
  - source: code/
    destination: /var/www/html
  - source: scripts/
    destination: /var/www/html/scripts
permissions:
  - object: /var/www/html
    pattern: "*.php"
    owner: ubuntu
    group: ubuntu
    mode: 444
    type:
      - directory
  - object: /var/www/html
    pattern: "scripts"
    owner: ubuntu
    group: ubuntu
    mode: 775
    type:
      - directory
  - object: /var/www/html/scripts
    pattern: "*"
    owner: ubuntu
    group: ubuntu
    mode: 775
    type:
      - file	
hooks:
  AfterInstall:
    - location: scripts/touchdate.sh
      timeout: 180s
      runas: root
